//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriverDownloader.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriverDownloader.Resources.common", typeof(common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to remove selected downloads?.
        /// </summary>
        internal static string DownloadList_Messages_Confirm {
            get {
                return ResourceManager.GetString("DownloadList_Messages_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string DownloadList_Tooltip_OpenFile {
            get {
                return ResourceManager.GetString("DownloadList_Tooltip_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Auto-Downloads On/Off.
        /// </summary>
        internal static string DownloadList_Tooltip_Toggle {
            get {
                return ResourceManager.GetString("DownloadList_Tooltip_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause All.
        /// </summary>
        internal static string DownloadList_U_PauseAll {
            get {
                return ResourceManager.GetString("DownloadList_U_PauseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        internal static string DownloadList_UI_ClearAll {
            get {
                return ResourceManager.GetString("DownloadList_UI_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Log.
        /// </summary>
        internal static string DownloadList_UI_ClearLog {
            get {
                return ResourceManager.GetString("DownloadList_UI_ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string DownloadList_UI_Completed {
            get {
                return ResourceManager.GetString("DownloadList_UI_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Try.
        /// </summary>
        internal static string DownloadList_UI_CurrentTry {
            get {
                return ResourceManager.GetString("DownloadList_UI_CurrentTry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current URL.
        /// </summary>
        internal static string DownloadList_UI_CurrentURL {
            get {
                return ResourceManager.GetString("DownloadList_UI_CurrentURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done (MB).
        /// </summary>
        internal static string DownloadList_UI_Done {
            get {
                return ResourceManager.GetString("DownloadList_UI_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Position.
        /// </summary>
        internal static string DownloadList_UI_EndPos {
            get {
                return ResourceManager.GetString("DownloadList_UI_EndPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DownloadList_UI_Error {
            get {
                return ResourceManager.GetString("DownloadList_UI_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string DownloadList_UI_File {
            get {
                return ResourceManager.GetString("DownloadList_UI_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job List.
        /// </summary>
        internal static string DownloadList_UI_JobList {
            get {
                return ResourceManager.GetString("DownloadList_UI_JobList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string DownloadList_UI_Left {
            get {
                return ResourceManager.GetString("DownloadList_UI_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string DownloadList_UI_Log {
            get {
                return ResourceManager.GetString("DownloadList_UI_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string DownloadList_UI_Pause {
            get {
                return ResourceManager.GetString("DownloadList_UI_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string DownloadList_UI_Progress {
            get {
                return ResourceManager.GetString("DownloadList_UI_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string DownloadList_UI_Rate {
            get {
                return ResourceManager.GetString("DownloadList_UI_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string DownloadList_UI_Remove {
            get {
                return ResourceManager.GetString("DownloadList_UI_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string DownloadList_UI_Size {
            get {
                return ResourceManager.GetString("DownloadList_UI_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (MB).
        /// </summary>
        internal static string DownloadList_UI_SizeMB {
            get {
                return ResourceManager.GetString("DownloadList_UI_SizeMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string DownloadList_UI_Start {
            get {
                return ResourceManager.GetString("DownloadList_UI_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start All.
        /// </summary>
        internal static string DownloadList_UI_StartAll {
            get {
                return ResourceManager.GetString("DownloadList_UI_StartAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Position.
        /// </summary>
        internal static string DownloadList_UI_StartPos {
            get {
                return ResourceManager.GetString("DownloadList_UI_StartPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string DownloadList_UI_State {
            get {
                return ResourceManager.GetString("DownloadList_UI_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string DownloadList_UI_Status {
            get {
                return ResourceManager.GetString("DownloadList_UI_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string DriverList_Columns_Category {
            get {
                return ResourceManager.GetString("DriverList_Columns_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Released.
        /// </summary>
        internal static string DriverList_Columns_Date {
            get {
                return ResourceManager.GetString("DriverList_Columns_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string DriverList_Columns_Download {
            get {
                return ResourceManager.GetString("DriverList_Columns_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Name.
        /// </summary>
        internal static string DriverList_Columns_DriverName {
            get {
                return ResourceManager.GetString("DriverList_Columns_DriverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string DriverList_Columns_Size {
            get {
                return ResourceManager.GetString("DriverList_Columns_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string DriverList_Columns_Version {
            get {
                return ResourceManager.GetString("DriverList_Columns_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string DriverList_Content_NA {
            get {
                return ResourceManager.GetString("DriverList_Content_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers List.
        /// </summary>
        internal static string DriverList_Tooltip_DriverList {
            get {
                return ResourceManager.GetString("DriverList_Tooltip_DriverList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Download Manager.
        /// </summary>
        internal static string MainForm_AppName {
            get {
                return ResourceManager.GetString("MainForm_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string MainForm_Buttons_Download {
            get {
                return ResourceManager.GetString("MainForm_Buttons_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select/UnSelect.
        /// </summary>
        internal static string MainForm_Buttons_Select {
            get {
                return ResourceManager.GetString("MainForm_Buttons_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Drivers.
        /// </summary>
        internal static string MainForm_Buttons_ViewDrivers {
            get {
                return ResourceManager.GetString("MainForm_Buttons_ViewDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Download Directory:.
        /// </summary>
        internal static string MainForm_Labels_DefaultDir {
            get {
                return ResourceManager.GetString("MainForm_Labels_DefaultDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 Found.
        /// </summary>
        internal static string MainForm_Labels_DefaultFound {
            get {
                return ResourceManager.GetString("MainForm_Labels_DefaultFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Found.
        /// </summary>
        internal static string MainForm_Labels_Found {
            get {
                return ResourceManager.GetString("MainForm_Labels_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighted items are\nalready in the target directory.
        /// </summary>
        internal static string MainForm_Labels_HighlightHint {
            get {
                return ResourceManager.GetString("MainForm_Labels_HighlightHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for drivers....
        /// </summary>
        internal static string MainForm_Labels_LookingForDrivers {
            get {
                return ResourceManager.GetString("MainForm_Labels_LookingForDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Version.
        /// </summary>
        internal static string MainForm_Labels_Mark {
            get {
                return ResourceManager.GetString("MainForm_Labels_Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Number.
        /// </summary>
        internal static string MainForm_Labels_Model {
            get {
                return ResourceManager.GetString("MainForm_Labels_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System.
        /// </summary>
        internal static string MainForm_Labels_OS {
            get {
                return ResourceManager.GetString("MainForm_Labels_OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an Issue.
        /// </summary>
        internal static string MainForm_Link_ReportIssue {
            get {
                return ResourceManager.GetString("MainForm_Link_ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\.
        /// </summary>
        internal static string MainForm_Links_DefaultDir {
            get {
                return ResourceManager.GetString("MainForm_Links_DefaultDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MainForm_Menu_About {
            get {
                return ResourceManager.GetString("MainForm_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MainForm_Menu_Exit {
            get {
                return ResourceManager.GetString("MainForm_Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MainForm_Menu_File {
            get {
                return ResourceManager.GetString("MainForm_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MainForm_Menu_Help {
            get {
                return ResourceManager.GetString("MainForm_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string MainForm_Menu_Preferences {
            get {
                return ResourceManager.GetString("MainForm_Menu_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string MainForm_Menu_Tools {
            get {
                return ResourceManager.GetString("MainForm_Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MainForm_MessageCaptions_Error {
            get {
                return ResourceManager.GetString("MainForm_MessageCaptions_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MainForm_MessageCaptions_Information {
            get {
                return ResourceManager.GetString("MainForm_MessageCaptions_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get product lists, please check your internet connection..
        /// </summary>
        internal static string MainForm_Messages_EmptyProductList {
            get {
                return ResourceManager.GetString("MainForm_Messages_EmptyProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow error, please check your input data..
        /// </summary>
        internal static string MainForm_Messages_Error {
            get {
                return ResourceManager.GetString("MainForm_Messages_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to seach drivers, please check your internet connection..
        /// </summary>
        internal static string MainForm_Messages_FailedToSearchDrivers {
            get {
                return ResourceManager.GetString("MainForm_Messages_FailedToSearchDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL format, please check the location field..
        /// </summary>
        internal static string MainForm_Messages_InvalidURL {
            get {
                return ResourceManager.GetString("MainForm_Messages_InvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select correct Model, Mark and OS..
        /// </summary>
        internal static string MainForm_Messages_ModelMarkOSNotAllSpecified {
            get {
                return ResourceManager.GetString("MainForm_Messages_ModelMarkOSNotAllSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no drivers selected..
        /// </summary>
        internal static string MainForm_Messages_NoDriverSelected {
            get {
                return ResourceManager.GetString("MainForm_Messages_NoDriverSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Found.
        /// </summary>
        internal static string MainForm_StaticText_Found {
            get {
                return ResourceManager.GetString("MainForm_StaticText_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Preferences_Buttons_Cancel {
            get {
                return ResourceManager.GetString("Preferences_Buttons_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Preferences_Buttons_Ok {
            get {
                return ResourceManager.GetString("Preferences_Buttons_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Preferences_Caption {
            get {
                return ResourceManager.GetString("Preferences_Caption", resourceCulture);
            }
        }
    }
}
